version: '3.9'

services:
  db:
      image: postgres:16
      restart: always
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        POSTGRES_DB: student_assistant
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    environment:
      - FRONTEND_URL=http://localhost
      - DB_NAME=student_assistant
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
    depends_on:
      - db
      - frontend

  frontend:
    build:
      context: ./frontend
    volumes:
      - react_build:/app/build
    command: echo "React build complete."

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - react_build:/usr/share/nginx/html
      - static_volume:/static
    depends_on:
      - backend

volumes:
  static_volume:
  react_build:
  postgres_data:
