# Generated by Django 5.1.6 on 2025-03-07 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_app', '0002_assignment_weight_grade_is_manual_grade_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='weight',
        ),
    ]
