# Generated by Django 5.1.6 on 2025-03-07 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_app', '0003_remove_assignment_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='is_manual',
        ),
    ]
