# Generated by Django 5.1.6 on 2025-03-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_app', '0004_remove_grade_is_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='weight',
        ),
        migrations.AddField(
            model_name='grade',
            name='credits',
            field=models.IntegerField(default=10),
        ),
    ]
