# Generated by Django 5.1.6 on 2025-03-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_app', '0005_remove_grade_weight_grade_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
