# Generated by Django 5.1.6 on 2025-03-18 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_app', '0007_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date_posted'], 'verbose_name_plural': 'News'},
        ),
    ]
